### ISSUE TITLE
error java.lang.NullPointerException: Cannot invoke method toInteger() on null object @ line 32

### ISSUE THREAD

**Issue by jgallen23** [obycode/smartthings-smartapps#1]
when I click Done, this error is logged:

`error java.lang.NullPointerException: Cannot invoke method toInteger() on null object @ line 32`

**Comment by obycode** [comment]
It looks like the Aeon Minimote device type is missing the "numButtons" field. I thought for sure that was there before. Anyway, I've posted a modified device type that should fix this.

**Comment by jgallen23** [comment]
I added new device type, updated my remote to use that device type and tried again and I got the same error

**Comment by obycode** [comment]
The place where the numButons field is set is only called during the initial connection, so maybe it didn't run when you changed the device?? Could you try deleting it and re-adding the device with this type.

**Comment by jgallen23** [comment]
Hmm. Any other ways?  Pairing these minimotes are a pain

**Comment by obycode** [comment]
Sorry for the delay, I've been away. You could always modify the device type to add a button which runs the code to initialize numButtons.

**Comment by jgallen23** [comment]
Thanks. I'll try that

**Comment by jgallen23** [comment]
ended up creating virtual buttons and using the built in button controller
